BagMVC/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BagLib;
using BagLib.Models;

namespace BagMVC.Controllers
{
    public class CountriesController : _BaseController
    {
  
        public CountriesController(BagContext context) : base(context)
        {
        }

        // GET: Countries
        public async Task<IActionResult> Index()
        {
            return base.View(
                await _context.GetCountriesAsync()
                );
        }



        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Country country = await _context.GetCountryAsync(id);

            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }



        //// GET: Countries/Create
        //public IActionResult Create()
        //{
        //    List<Currency> currencies = new List<Currency>();

        //    currencies.Add(new Currency((int)CurrencyType.Dolar, CurrencyType.Dolar.ToString()));
        //    currencies.Add(new Currency((int)CurrencyType.Pound, CurrencyType.Pound.ToString()));
        //    currencies.Add(new Currency((int)CurrencyType.Jen, CurrencyType.Jen.ToString()));

        //    ViewData["Currencies"] = new SelectList(currencies, "Id", "Name");

        //    return View();
        //}

        //// POST: Countries/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("CountryId,Name,CurrencyType")] Country country)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(country);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(country);
        //}

        // GET: Countries/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var country = await _context.Country.FindAsync(id);
        //    if (country == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(country);
        //}

        //// POST: Countries/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("CountryId,Name,CurrencyType")] Country country)
        //{
        //    if (id != country.CountryId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(country);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!CountryExists(country.CountryId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(country);
        //}

        // GET: Countries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.CountryId == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var country = await _context.Country.FindAsync(id);
            _context.Country.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update()
        {
            ApiCountryLib.ApiCountryClient myApi = new ApiCountryLib.ApiCountryClient("https://restcountries.com", 2);

            var myResult = await myApi.GetCountries();

            foreach ( var country in myResult )
            {
                // 1. Compruebo que exista país
                var dbCountry = await _context.GetCountryByNameAsync(country.name);

                // 1.2 Si no existe, inserto el país
                if ( dbCountry==null )
                {
                    dbCountry = new Country(country.name, country.alpha3Code);

                    dbCountry= await _context.InsertCountryAsync(dbCountry);
                }

                if ( country.currencies!=null )
                {
                    // Para cada moneda
                    foreach (var currency in country.currencies )
                    {
                        // 2. Compruebo si existe la moneda
                        var dbCurrency = await _context.GetCurrencyAsync(currency.code);

                        // 2.1 Si no existe, inserto la moneda
                        if ( dbCurrency == null )
                        {
                            dbCurrency = new(currency.code, currency.name, currency.symbol);

                            dbCurrency = await _context.InsertCurrencyAsync(dbCurrency);

                            // Sólo añade moneda a un país cuándo inserta
                            //// Si modifico las monedas relacionadas, guardo cambios
                            //dbCountry.Currencies.Add(dbCurrency);

                            //await _context.SaveChangesAsync();
                        }

                        // 3. Compruebo si el país de MI base de datos tiene esa moneda
                        var currencyCountry = dbCountry.Currencies.FirstOrDefault(d => d.Code == dbCurrency.Code);

                        // 3.1 Si no la tiene, la inserto
                        if ( currencyCountry == null )
                        {
                            dbCountry.Currencies.Add(dbCurrency);

                            await _context.SaveChangesAsync();
                        }
                    }
                }
                else
                {
                    // Países sin moneda
                }

                


            }
            

            return RedirectToAction(nameof(Index));
        }

        private bool CountryExists(int id)
        {
            return _context.Country.Any(e => e.CountryId == id);
        }
    }
}

BagMVC/Views/Countries/Create.cshtml
@model BagLib.Models.Country

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrencyType" class="control-label"></label>
                <select asp-for="CurrencyType" asp-items="ViewBag.Currencies" class="form-control"></select>
                <span asp-validation-for="CurrencyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BagMVC/Views/Countries/Delete.cshtml
@model BagLib.Models.Country

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrencyType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrencyType)
        </dd>*@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CountryId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BagMVC/Views/Countries/Details.cshtml
@model BagLib.Models.Country

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currencies)
        </dt>
        <dd class = "col-sm-10">
            @*@Html.DisplayFor(model => model.CurrencyType)*@

            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Currencies.FirstOrDefault().Symbol)</th>
                        <th>@Html.DisplayNameFor(m => m.Currencies.FirstOrDefault().Code)</th>
                        <th>@Html.DisplayNameFor(m => m.Currencies.FirstOrDefault().Name)</th>
                    </tr>
                </thead>
                <tbody>
            @foreach (var c in Model.Currencies)
            {
                   <tr>
                        <td class="coin">@Html.DisplayFor(m => c.Symbol)   </td>
                        <td> @Html.DisplayFor(m => c.Code) </td>
                        <td>@Html.DisplayFor(m => c.Name) </td>
                    </tr>                       
            }
 
                </tbody>
            </table>


        </dd>
    </dl>
</div>
<div>

    <a asp-action="Index">Back to List</a>
</div>

BagMVC/Views/Countries/Edit.cshtml
@model BagLib.Models.Country

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CountryId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrencyType" class="control-label"></label>
                <select asp-for="CurrencyType" class="form-control"></select>
                <span asp-validation-for="CurrencyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BagMVC/Views/Countries/Index.cshtml
@model IEnumerable<BagLib.Models.Country>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>



<div class="row">
    <div class="col-6">
        <input id="my-locate" type="text" />
        <button id="bt-locate" class="btn btn-primary">Buscar</button>
        <button id="bt-reset" class="btn btn-dark">Resetear</button>
        <button id="bt-another" class="btn btn-dark">Función anónima</button>
    </div>
    <div class="col-6">
        <p>
            @*<a asp-action="Create">Create New</a>*@
            <a asp-action="Update">Actualizar desde API</a>
        </p>
    </div>
</div>
<div id="my-message" class="alert alert-warning">
    Introduce un texto válido, por favor
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th colspan="2">
                @Html.DisplayNameFor(model => model.Currencies)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="@item.Name.ToLower()">
            <td>
                <span>
                    <a asp-controller="Countries" asp-action="Details" asp-route-id="@item.CountryId" >@Html.DisplayFor(modelItem => item.Name)</a> 
                </span>                
            </td>
            <td class="coin">
                @*@Html.DisplayFor(modelItem => item.CurrencyType)*@
                @foreach (var c in item.Currencies)
                {
                    @Html.DisplayFor(m => c.Symbol)                        
                }
               
            </td>
            <td>
                (@item.Currencies.Count)
            </td>
            <td>
            @*    <a asp-action="Edit" asp-route-id="@item.CountryId">Edit</a> |*@
                <a asp-action="Details" asp-route-id="@item.CountryId">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts
{
<script>

    function searchCutre() {
        console.log("Buscando cutremente...");

        $("tr").hide();

        var text = $("#my-locate").val().toLowerCase().trim();

        console.log("el texto a buscar es: ", text);

        //if ( text=="" ) {
        if ( text==="" ) {
            $("#my-message").show();
        }
        else {
            $("#my-message").hide();

            $("." + text ).show();
        }
    }

    function searchMenosCutre() {

        var text = $("#my-locate").val().toLowerCase().trim();

        $("table tbody tr").each( function() {

            // Escribo el texto de cada elemento de la colección: de cada fila
            //console.log( $(this).text() );

            //console.log( $(this).text().toLowerCase().indexOf(text) );

            if ( $(this).text().toLowerCase().indexOf(text) > -1 ) {
                $(this).show();
            }
            else {
                $(this).hide();
            }

        } );
    }

    function resetCountries() {

        $("tr").show();
    }

    function initialize() {
        //alert("cargando");
        // Antes buscaba de forma cutre
        //$("#bt-locate").click(searchCutre);

        // Ahora buscamos mejor
        $("#bt-locate").click(searchMenosCutre);

        $("#bt-reset").click(resetCountries);

        $("#bt-another").click( function () {
            console.log("Esto es una función anónima");

            var unNumero = 8;

            if ( unNumero=="8") {
                console.log("Funciona con == comprar un entero y un string");
            }

            if ( unNumero==="8") {
                console.log("¿Funciona con === comprar un entero y un string?");
            }

            if ( unNumero === parseInt("8")) {
                console.log("Funciona con === comprar un entero y un string sólo cuándo coinciden los tipos");
            }
        } );
    }

    $().ready(initialize);
</script>
}